version: "3.8"
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - published: 4001
        target: 4001
      - published: 5001
        target: 5001
      - published: 8080
        target: 8080
    volumes:
      - "./ipfs/export:/export"
      - "./ipfs/data:/data/ipfs"
